# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"file_exists": "02_aug.ipynb",
         "ds_file_exists": "02_aug.ipynb",
         "filter_for_exists": "02_aug.ipynb",
         "drop_missing_files": "02_aug.ipynb",
         "add_ds": "02_aug.ipynb",
         "remove_special_characters": "02_aug.ipynb",
         "chars_to_ignore_regex": "02_aug.ipynb",
         "extract_all_chars": "02_aug.ipynb",
         "get_char_vocab": "02_aug.ipynb",
         "process_vocab": "02_aug.ipynb",
         "extract_vocab": "02_aug.ipynb",
         "speech_file_to_array": "01_data.ipynb",
         "speech_file_to_array_fn": "02_aug.ipynb"}

modules = ["data.py",
           "training.py"]

doc_url = "https://morganmcg1.github.io/xlsr_finetune/"

git_url = "https://github.com/morganmcg1/xlsr_finetune/tree/master/"

def custom_doc_links(name): return None
