# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"file_exists": "01_data.ipynb",
         "ds_file_exists": "01_data.ipynb",
         "filter_for_exists": "01_data.ipynb",
         "drop_missing_files": "01_data.ipynb",
         "add_ds": "01_data.ipynb",
         "merge_ds": "01_data.ipynb",
         "remove_special_characters": "01_data.ipynb",
         "chars_to_ignore_regex": "01_data.ipynb",
         "extract_all_chars": "01_data.ipynb",
         "get_char_vocab": "01_data.ipynb",
         "process_vocab": "01_data.ipynb",
         "extract_vocab": "01_data.ipynb",
         "speech_file_to_array": "01_data.ipynb",
         "DataCollatorCTCWithPadding": "03_training.ipynb",
         "wer_metric": "04_evaluation.ipynb",
         "compute_wer_metric": "03_training.ipynb",
         "setup_wandb": "03_training.ipynb",
         "evaluate_xlsr": "04_evaluation.ipynb"}

modules = ["data.py",
           "augmentation.py",
           "training.py",
           "evaluation.py"]

doc_url = "https://morganmcg1.github.io/xlsr_finetune/"

git_url = "https://github.com/morganmcg1/xlsr_finetune/tree/master/"

def custom_doc_links(name): return None
