# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/02_aug.ipynb (unless otherwise specified).

__all__ = []

# Cell
import os
import re
import json
from pathlib import Path
from functools import partial

# Cell
from datasets import load_dataset, load_metric, concatenate_datasets
import torchaudio