# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/05_wandb_utils.ipynb (unless otherwise specified).

__all__ = ['setup_wandb']

# Cell
#all_slow
import wandb
import librosa
import torchaudio
import numpy as np
from fastcore.basics import *
from datasets import Dataset, load_dataset

# Cell
def setup_wandb(entity='wandb', project_name='xlsr', log_model=True):
    import os
    import wandb
    # Set W&B user name
    os.environ["WANDB_ENTITY"] = entity

    # Set W&B project name. xlsr is a public W&B project
    os.environ["WANDB_PROJECT"] = project_name

    # Log your trained model to W&B as an Artifact
    if log_model: os.environ["WANDB_LOG_MODEL"] = 'true'

    wandb.login()

    return entity, project_name